with open('app/api/v1/endpoints/schedules.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join([
        'from fastapi import APIRouter, Depends, HTTPException',
        'from sqlalchemy.orm import Session',
        'from app.db.session import get_db',
        'from app.models.schedule import Schedule, ScheduleStatus',
        'from app.models.route import Route',
        'from app.models.bus import Bus',
        'from app.models.seat import Seat, SeatStatus',
        'from pydantic import BaseModel',
        'from datetime import datetime',
        'from uuid import UUID',
        'import uuid',
        '',
        'router = APIRouter()',
        '',
        'class ScheduleCreate(BaseModel):',
        '    route_id: UUID',
        '    bus_id: UUID',
        '    departure_time: str',
        '    price_normal: float',
        '    price_semicama: float',
        '    price_cama: float',
        '    terminal_fee: float = 2.50',
        '',
        '@router.get("/")',
        'def list_schedules(db: Session = Depends(get_db)):',
        '    schedules = db.query(Schedule).order_by(Schedule.departure_time).all()',
        '    result = []',
        '    for s in schedules:',
        '        route = db.query(Route).filter(Route.id == s.route_id).first()',
        '        bus = db.query(Bus).filter(Bus.id == s.bus_id).first()',
        '        seats_total = db.query(Seat).filter(Seat.schedule_id == s.id).count()',
        '        seats_available = db.query(Seat).filter(Seat.schedule_id == s.id, Seat.status == SeatStatus.AVAILABLE).count()',
        '        result.append({',
        '            "id": str(s.id),',
        '            "origin": route.origin if route else "-",',
        '            "destination": route.destination if route else "-",',
        '            "company": bus.company if bus else "-",',
        '            "bus_type": bus.bus_type.value if bus else "-",',
        '            "plate": bus.plate if bus else "-",',
        '            "departure_time": s.departure_time.isoformat(),',
        '            "arrival_time": s.arrival_time.isoformat(),',
        '            "price_normal": s.price_normal,',
        '            "price_semicama": s.price_semicama,',
        '            "price_cama": s.price_cama,',
        '            "terminal_fee": s.terminal_fee,',
        '            "status": s.status.value,',
        '            "seats_total": seats_total,',
        '            "seats_available": seats_available,',
        '        })',
        '    return {"schedules": result, "total": len(result)}',
        '',
        '@router.post("/")',
        'def create_schedule(data: ScheduleCreate, db: Session = Depends(get_db)):',
        '    route = db.query(Route).filter(Route.id == data.route_id).first()',
        '    if not route:',
        '        raise HTTPException(status_code=404, detail="Ruta no encontrada")',
        '    bus = db.query(Bus).filter(Bus.id == data.bus_id).first()',
        '    if not bus:',
        '        raise HTTPException(status_code=404, detail="Bus no encontrado")',
        '    dep = datetime.fromisoformat(data.departure_time)',
        '    from datetime import timedelta',
        '    arr = dep + timedelta(hours=route.duration_hours)',
        '    schedule = Schedule(',
        '        id=uuid.uuid4(),',
        '        route_id=data.route_id,',
        '        bus_id=data.bus_id,',
        '        departure_time=dep,',
        '        arrival_time=arr,',
        '        price_normal=data.price_normal,',
        '        price_semicama=data.price_semicama,',
        '        price_cama=data.price_cama,',
        '        terminal_fee=data.terminal_fee,',
        '        status=ScheduleStatus.ACTIVE',
        '    )',
        '    db.add(schedule)',
        '    db.flush()',
        '    seats_created = 0',
        '    for floor in [1, 2]:',
        '        for row in range(1, 11):',
        '            for col in range(1, 3):',
        '                num = f"{chr(65) if floor==1 else chr(66)}{row}{col}"',
        '                seat = Seat(',
        '                    id=uuid.uuid4(),',
        '                    schedule_id=schedule.id,',
        '                    seat_number=num,',
        '                    floor=floor,',
        '                    row=row,',
        '                    column=col,',
        '                    status=SeatStatus.AVAILABLE',
        '                )',
        '                db.add(seat)',
        '                seats_created += 1',
        '    db.commit()',
        '    return {"message": "Horario creado", "schedule_id": str(schedule.id), "seats_created": seats_created}',
        '',
        '@router.delete("/{schedule_id}")',
        'def cancel_schedule(schedule_id: UUID, db: Session = Depends(get_db)):',
        '    schedule = db.query(Schedule).filter(Schedule.id == schedule_id).first()',
        '    if not schedule:',
        '        raise HTTPException(status_code=404, detail="Horario no encontrado")',
        '    schedule.status = ScheduleStatus.CANCELLED',
        '    db.commit()',
        '    return {"message": "Horario cancelado"}',
        '',
        '@router.get("/buses")',
        'def list_buses(db: Session = Depends(get_db)):',
        '    buses = db.query(Bus).filter(Bus.is_active == True).all()',
        '    return {"buses": [{"id": str(b.id), "company": b.company, "plate": b.plate, "bus_type": b.bus_type.value} for b in buses]}',
        '',
        '@router.get("/routes")',
        'def list_routes(db: Session = Depends(get_db)):',
        '    routes = db.query(Route).filter(Route.is_active == True).all()',
        '    return {"routes": [{"id": str(r.id), "origin": r.origin, "destination": r.destination, "duration_hours": r.duration_hours} for r in routes]}',
    ]) + '\n')
print('OK: schedules.py actualizado')