with open('app/api/v1/endpoints/tickets.py', 'w', encoding='utf-8') as f:
    f.write(
'from fastapi import APIRouter, Depends, HTTPException\n'
'from fastapi.responses import Response\n'
'from sqlalchemy.orm import Session\n'
'from uuid import UUID\n'
'from app.db.session import get_db\n'
'from app.services.ticket_service import get_ticket\n'
'from app.utils.pdf_generator import generate_ticket_pdf\n'
'from app.utils.qr_generator import validate_qr_token\n'
'from app.models.booking import Booking, BookingStatus\n'
'\n'
'router = APIRouter()\n'
'\n'
'@router.get(\"/{booking_id}\")\n'
'def get_ticket_info(booking_id: UUID, db: Session = Depends(get_db)):\n'
'    result = get_ticket(db, booking_id)\n'
'    if not result:\n'
'        raise HTTPException(status_code=404, detail=\"Ticket no encontrado\")\n'
'    return result\n'
'\n'
'@router.get(\"/{booking_id}/pdf\")\n'
'def download_pdf(booking_id: UUID, db: Session = Depends(get_db)):\n'
'    result = get_ticket(db, booking_id)\n'
'    if not result:\n'
'        raise HTTPException(status_code=404, detail=\"Ticket no encontrado\")\n'
'    pdf = generate_ticket_pdf(result)\n'
'    filename = f\"ticket_{booking_id}.pdf\"\n'
'    return Response(content=pdf, media_type=\"application/pdf\", headers={\"Content-Disposition\": f\"attachment; filename={filename}\"})\n'
'\n'
'@router.post(\"/validate\")\n'
'def validate_ticket(token: str, db: Session = Depends(get_db)):\n'
'    payload = validate_qr_token(token)\n'
'    if not payload:\n'
'        raise HTTPException(status_code=400, detail=\"Token invalido\")\n'
'    booking = db.query(Booking).filter(Booking.id == UUID(payload[\"booking_id\"])).first()\n'
'    if not booking:\n'
'        raise HTTPException(status_code=404, detail=\"Reserva no encontrada\")\n'
'    if booking.is_used:\n'
'        raise HTTPException(status_code=400, detail=\"Ticket ya usado\")\n'
'    booking.is_used = True\n'
'    booking.status = BookingStatus.USED\n'
'    db.commit()\n'
'    return {\"message\": \"Ticket validado\", \"passenger\": booking.passenger_name}\n'
    )
print('OK: tickets.py')