lines = [
'from reportlab.lib.pagesizes import A4',
'from reportlab.lib import colors',
'from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle',
'from reportlab.lib.units import cm',
'from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image',
'from reportlab.lib.enums import TA_CENTER',
'from io import BytesIO',
'import qrcode',
'',
'NAVY = colors.HexColor("#1B2A6B")',
'GOLD = colors.HexColor("#D4AF37")',
'',
'def generate_ticket_pdf(t: dict) -> bytes:',
'    buf = BytesIO()',
'    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)',
'    styles = getSampleStyleSheet()',
'    lbl = ParagraphStyle("lbl", parent=styles["Normal"], textColor=NAVY, fontSize=9, fontName="Helvetica-Bold")',
'    val = ParagraphStyle("val", parent=styles["Normal"], textColor=colors.black, fontSize=11)',
'    ctr = ParagraphStyle("ctr", parent=styles["Normal"], textColor=colors.white, fontSize=20, alignment=TA_CENTER)',
'    sub = ParagraphStyle("sub", parent=styles["Normal"], textColor=GOLD, fontSize=12, alignment=TA_CENTER)',
'    elems = []',
'    hdr = Table([[Paragraph("BOLIVIA BUS", ctr)], [Paragraph("Ticket de Viaje", sub)]], colWidths=[17*cm])',
'    hdr.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),NAVY),("ALIGN",(0,0),(-1,-1),"CENTER"),("TOPPADDING",(0,0),(-1,-1),12),("BOTTOMPADDING",(0,0),(-1,-1),12)]))',
'    elems.append(hdr)',
'    elems.append(Spacer(1, 0.5*cm))',
'    origin = t.get("origin", "")',
'    dest = t.get("destination", "")',
'    dep = t.get("departure_time", "")',
'    rows = [',
'        [Paragraph("PASAJERO", lbl), Paragraph(str(t.get("passenger_name","")).upper(), val)],',
'        [Paragraph("CI", lbl), Paragraph(str(t.get("passenger_ci","")), val)],',
'        [Paragraph("RUTA", lbl), Paragraph(f"{origin} -> {dest}", val)],',
'        [Paragraph("SALIDA", lbl), Paragraph(str(dep), val)],',
'        [Paragraph("ASIENTO", lbl), Paragraph(f"{t.get(chr(115)+chr(101)+chr(97)+chr(116)+chr(95)+chr(110)+chr(117)+chr(109)+chr(98)+chr(101)+chr(114),\"\")} Piso {t.get(chr(102)+chr(108)+chr(111)+chr(111)+chr(114),\"\")}", val)],',
'        [Paragraph("EMPRESA", lbl), Paragraph(f"{t.get(chr(99)+chr(111)+chr(109)+chr(112)+chr(97)+chr(110)+chr(121),\"\")} - {t.get(chr(98)+chr(117)+chr(115)+chr(95)+chr(116)+chr(121)+chr(112)+chr(101),\"\")}", val)],',
'        [Paragraph("PRECIO BASE", lbl), Paragraph(f"Bs. {t.get(chr(98)+chr(97)+chr(115)+chr(101)+chr(95)+chr(112)+chr(114)+chr(105)+chr(99)+chr(101),0):.2f}", val)],',
'        [Paragraph("TERMINAL", lbl), Paragraph(f"Bs. {t.get(chr(116)+chr(101)+chr(114)+chr(109)+chr(105)+chr(110)+chr(97)+chr(108)+chr(95)+chr(102)+chr(101)+chr(101),0):.2f}", val)],',
'        [Paragraph("TOTAL", lbl), Paragraph(f"Bs. {t.get(chr(116)+chr(111)+chr(116)+chr(97)+chr(108)+chr(95)+chr(112)+chr(114)+chr(105)+chr(99)+chr(101),0):.2f}", val)],',
'    ]',
'    tbl = Table(rows, colWidths=[5*cm, 12*cm])',
'    tbl.setStyle(TableStyle([("GRID",(0,0),(-1,-1),0.5,colors.lightgrey),("BACKGROUND",(0,0),(0,-1),colors.HexColor("#F0F4FF")),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),("LEFTPADDING",(0,0),(-1,-1),10)]))',
'    elems.append(tbl)',
'    elems.append(Spacer(1, 0.5*cm))',
'    qr = qrcode.QRCode(version=1, box_size=6, border=2)',
'    qr.add_data(t.get("qr_token",""))',
'    qr.make(fit=True)',
'    qr_img = qr.make_image(fill_color="black", back_color="white")',
'    qb = BytesIO()',
'    qr_img.save(qb, format="PNG")',
'    qb.seek(0)',
'    qr_rl = Image(qb, width=4*cm, height=4*cm)',
'    qt = Table([[qr_rl, Paragraph("Presenta este QR al conductor para validar tu pasaje.", ParagraphStyle("qt", parent=styles["Normal"], fontSize=10, textColor=NAVY))]], colWidths=[5*cm, 12*cm])',
'    qt.setStyle(TableStyle([("ALIGN",(0,0),(0,0),"CENTER"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("BOX",(0,0),(-1,-1),1,NAVY),("TOPPADDING",(0,0),(-1,-1),10),("BOTTOMPADDING",(0,0),(-1,-1),10)]))',
'    elems.append(qt)',
'    elems.append(Spacer(1, 0.3*cm))',
'    elems.append(Paragraph("Bolivia Bus | Sistema Integral de Ticketing Terrestre | boliviabus.bo", ParagraphStyle("ft", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))',
'    doc.build(elems)',
'    buf.seek(0)',
'    return buf.getvalue()',
]
with open("app/utils/pdf_generator.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("pdf_generator.py escrito")