# websocket manager
lines1 = [
    'from fastapi import WebSocket',
    'from typing import List',
    'import json',
    '',
    'class ConnectionManager:',
    '    def __init__(self):',
    '        self.active_connections: List[WebSocket] = []',
    '',
    '    async def connect(self, websocket: WebSocket):',
    '        await websocket.accept()',
    '        self.active_connections.append(websocket)',
    '',
    '    def disconnect(self, websocket: WebSocket):',
    '        if websocket in self.active_connections:',
    '            self.active_connections.remove(websocket)',
    '',
    '    async def broadcast(self, data: dict):',
    '        dead = []',
    '        for conn in self.active_connections:',
    '            try:',
    '                await conn.send_text(json.dumps(data))',
    '            except:',
    '                dead.append(conn)',
    '        for d in dead:',
    '            self.active_connections.remove(d)',
    '',
    'manager = ConnectionManager()',
]
with open('app/core/websocket.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines1) + '\n')
print('OK: websocket.py')

# tracking endpoint
lines2 = [
    'from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Depends',
    'from sqlalchemy.orm import Session',
    'from app.db.session import get_db',
    'from app.models.bus_location import BusLocation',
    'from app.models.bus import Bus',
    'from app.core.websocket import manager',
    'from datetime import datetime',
    'import uuid',
    '',
    'router = APIRouter()',
    '',
    '@router.websocket("/ws/tracking")',
    'async def tracking_ws(websocket: WebSocket):',
    '    await manager.connect(websocket)',
    '    try:',
    '        while True:',
    '            await websocket.receive_text()',
    '    except WebSocketDisconnect:',
    '        manager.disconnect(websocket)',
    '',
    '@router.post("/update")',
    'async def update_location(',
    '    bus_id: str,',
    '    latitude: float,',
    '    longitude: float,',
    '    speed_kmh: float = 0.0,',
    '    heading: float = 0.0,',
    '    status: str = "en_ruta",',
    '    db: Session = Depends(get_db)',
    '):',
    '    loc = BusLocation(',
    '        id=uuid.uuid4(),',
    '        bus_id=uuid.UUID(bus_id),',
    '        latitude=latitude,',
    '        longitude=longitude,',
    '        speed_kmh=speed_kmh,',
    '        heading=heading,',
    '        status=status,',
    '        timestamp=datetime.utcnow()',
    '    )',
    '    db.add(loc)',
    '    db.commit()',
    '    bus = db.query(Bus).filter(Bus.id == uuid.UUID(bus_id)).first()',
    '    await manager.broadcast({',
    '        "type": "location_update",',
    '        "bus_id": bus_id,',
    '        "company": bus.company if bus else "Desconocido",',
    '        "bus_type": bus.bus_type.value if bus else "normal",',
    '        "plate": bus.plate if bus else "",',
    '        "latitude": latitude,',
    '        "longitude": longitude,',
    '        "speed_kmh": speed_kmh,',
    '        "status": status,',
    '        "timestamp": datetime.utcnow().isoformat()',
    '    })',
    '    return {"ok": True}',
    '',
    '@router.get("/latest")',
    'def get_latest(db: Session = Depends(get_db)):',
    '    buses = db.query(Bus).filter(Bus.is_active == True).all()',
    '    result = []',
    '    for bus in buses:',
    '        loc = db.query(BusLocation).filter(',
    '            BusLocation.bus_id == bus.id',
    '        ).order_by(BusLocation.timestamp.desc()).first()',
    '        if loc:',
    '            result.append({',
    '                "bus_id": str(bus.id),',
    '                "company": bus.company,',
    '                "bus_type": bus.bus_type.value,',
    '                "plate": bus.plate,',
    '                "latitude": loc.latitude,',
    '                "longitude": loc.longitude,',
    '                "speed_kmh": loc.speed_kmh,',
    '                "status": loc.status,',
    '                "timestamp": loc.timestamp.isoformat()',
    '            })',
    '    return {"buses": result}',
]
with open('app/api/v1/endpoints/tracking.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines2) + '\n')
print('OK: tracking.py')

# gps simulator
lines3 = [
    'import asyncio',
    'import httpx',
    '',
    'RUTAS = {',
    '    "La Paz - Cochabamba": [',
    '        (-16.5000, -68.1500),',
    '        (-16.6000, -68.0000),',
    '        (-16.7500, -67.8000),',
    '        (-16.9000, -67.5000),',
    '        (-17.0500, -67.2000),',
    '        (-17.1500, -66.8000),',
    '        (-17.2500, -66.5000),',
    '        (-17.3800, -66.1600),',
    '    ],',
    '    "La Paz - Oruro": [',
    '        (-16.5000, -68.1500),',
    '        (-16.7000, -68.0500),',
    '        (-16.9000, -67.9500),',
    '        (-17.1500, -67.8000),',
    '        (-17.3800, -67.9000),',
    '        (-17.5000, -67.8500),',
    '        (-17.7200, -67.6500),',
    '        (-17.9800, -67.1400),',
    '    ],',
    '    "Cochabamba - Santa Cruz": [',
    '        (-17.3800, -66.1600),',
    '        (-17.4500, -65.8000),',
    '        (-17.5500, -65.4000),',
    '        (-17.6500, -65.0000),',
    '        (-17.7500, -64.6000),',
    '        (-17.8000, -64.2000),',
    '        (-17.8500, -63.8000),',
    '        (-17.7800, -63.1800),',
    '    ],',
    '}',
    '',
    'async def simulate_bus(bus_id: str, route_name: str, interval: int = 4):',
    '    points = RUTAS.get(route_name, list(RUTAS.values())[0])',
    '    idx = 0',
    '    direction = 1',
    '    async with httpx.AsyncClient() as client:',
    '        while True:',
    '            lat, lng = points[idx]',
    '            try:',
    '                await client.post(',
    '                    "http://localhost:8000/api/v1/tracking/update",',
    '                    params={',
    '                        "bus_id": bus_id,',
    '                        "latitude": lat,',
    '                        "longitude": lng,',
    '                        "speed_kmh": 85.0,',
    '                        "status": "en_ruta"',
    '                    }',
    '                )',
    '                print(f"Bus {bus_id[:8]}... {route_name} punto {idx+1}/{len(points)}")',
    '            except Exception as e:',
    '                print(f"Error: {e}")',
    '            idx += direction',
    '            if idx >= len(points) - 1:',
    '                direction = -1',
    '            elif idx <= 0:',
    '                direction = 1',
    '            await asyncio.sleep(interval)',
    '',
    'async def main():',
    '    import sys',
    '    sys.path.insert(0, ".")',
    '    from app.db.session import SessionLocal',
    '    from app.models.bus import Bus',
    '    db = SessionLocal()',
    '    buses = db.query(Bus).filter(Bus.is_active == True).all()',
    '    db.close()',
    '    routes_list = list(RUTAS.keys())',
    '    tasks = []',
    '    for i, bus in enumerate(buses):',
    '        route = routes_list[i % len(routes_list)]',
    '        print(f"Simulando: {bus.company} en {route}")',
    '        tasks.append(simulate_bus(str(bus.id), route))',
    '    await asyncio.gather(*tasks)',
    '',
    'if __name__ == "__main__":',
    '    asyncio.run(main())',
]
with open('gps_simulator.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines3) + '\n')
print('OK: gps_simulator.py')