import os

schemas = {
    'app/schemas/user.py': [
        'from pydantic import BaseModel, EmailStr',
        'from typing import Optional',
        'from uuid import UUID',
        'from datetime import datetime',
        '',
        'class UserCreate(BaseModel):',
        '    full_name: str',
        '    ci: str',
        '    ci_extension: Optional[str] = None',
        '    email: EmailStr',
        '    phone: Optional[str] = None',
        '    password: str',
        '',
        'class UserLogin(BaseModel):',
        '    email: EmailStr',
        '    password: str',
        '',
        'class UserResponse(BaseModel):',
        '    id: UUID',
        '    full_name: str',
        '    ci: str',
        '    ci_extension: Optional[str] = None',
        '    email: str',
        '    phone: Optional[str] = None',
        '    is_active: bool',
        '    is_admin: bool',
        '    created_at: datetime',
        '    class Config:',
        '        from_attributes = True',
        '',
        'class Token(BaseModel):',
        '    access_token: str',
        '    token_type: str = "bearer"',
        '    user: UserResponse',
    ],
    'app/schemas/route.py': [
        'from pydantic import BaseModel',
        'from typing import Optional, List',
        'from uuid import UUID',
        'from datetime import datetime',
        '',
        'class RouteResponse(BaseModel):',
        '    id: UUID',
        '    origin: str',
        '    destination: str',
        '    distance_km: float',
        '    duration_hours: float',
        '    is_active: bool',
        '    class Config:',
        '        from_attributes = True',
        '',
        'class SearchRequest(BaseModel):',
        '    origin: str',
        '    destination: str',
        '    date: str',
        '    passengers: int = 1',
        '',
        'class ScheduleResponse(BaseModel):',
        '    id: UUID',
        '    route_id: UUID',
        '    bus_id: UUID',
        '    departure_time: datetime',
        '    arrival_time: datetime',
        '    price_normal: float',
        '    price_semicama: float',
        '    price_cama: float',
        '    terminal_fee: float',
        '    status: str',
        '    available_seats: Optional[int] = None',
        '    origin: Optional[str] = None',
        '    destination: Optional[str] = None',
        '    company: Optional[str] = None',
        '    bus_type: Optional[str] = None',
        '    duration_hours: Optional[float] = None',
        '    class Config:',
        '        from_attributes = True',
    ],
    'app/schemas/booking.py': [
        'from pydantic import BaseModel',
        'from typing import Optional',
        'from uuid import UUID',
        'from datetime import datetime',
        '',
        'class SeatResponse(BaseModel):',
        '    id: UUID',
        '    seat_number: str',
        '    floor: int',
        '    row: int',
        '    column: int',
        '    status: str',
        '    class Config:',
        '        from_attributes = True',
        '',
        'class BookingCreate(BaseModel):',
        '    schedule_id: UUID',
        '    seat_id: UUID',
        '    passenger_name: str',
        '    passenger_ci: str',
        '',
        'class BookingResponse(BaseModel):',
        '    id: UUID',
        '    passenger_name: str',
        '    passenger_ci: str',
        '    base_price: float',
        '    terminal_fee: float',
        '    total_price: float',
        '    status: str',
        '    qr_token: Optional[str] = None',
        '    created_at: datetime',
        '    class Config:',
        '        from_attributes = True',
    ],
    'app/schemas/ticket.py': [
        'from pydantic import BaseModel',
        'from uuid import UUID',
        'from datetime import datetime',
        '',
        'class TicketResponse(BaseModel):',
        '    booking_id: UUID',
        '    passenger_name: str',
        '    passenger_ci: str',
        '    origin: str',
        '    destination: str',
        '    departure_time: datetime',
        '    seat_number: str',
        '    floor: int',
        '    bus_type: str',
        '    company: str',
        '    base_price: float',
        '    terminal_fee: float',
        '    total_price: float',
        '    qr_token: str',
        '    status: str',
    ],
}

for filepath, lines in schemas.items():
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'OK: {filepath}')