files = {
'app/services/seat_service.py': [
'from sqlalchemy.orm import Session',
'from sqlalchemy import select',
'from uuid import UUID',
'from datetime import datetime, timedelta',
'from app.models.seat import Seat, SeatStatus',
'from app.models.schedule import Schedule',
'',
'def get_seat_map(db: Session, schedule_id: UUID):',
'    seats = db.query(Seat).filter(Seat.schedule_id == schedule_id).order_by(Seat.floor, Seat.row, Seat.column).all()',
'    floor1 = []',
'    floor2 = []',
'    for s in seats:',
'        data = {',
'            "id": str(s.id),',
'            "seat_number": s.seat_number,',
'            "floor": s.floor,',
'            "row": s.row,',
'            "column": s.column,',
'            "status": s.status.value,',
'        }',
'        if s.floor == 1:',
'            floor1.append(data)',
'        else:',
'            floor2.append(data)',
'    return {"floor_1": floor1, "floor_2": floor2, "total": len(seats)}',
'',
'def reserve_seat_with_lock(db: Session, seat_id: UUID, minutes: int = 15):',
'    seat = db.query(Seat).filter(Seat.id == seat_id).with_for_update().first()',
'    if not seat:',
'        return None, "Asiento no encontrado"',
'    if seat.status != SeatStatus.AVAILABLE:',
'        return None, "Asiento no disponible"',
'    seat.status = SeatStatus.RESERVED',
'    seat.reserved_until = datetime.utcnow() + timedelta(minutes=minutes)',
'    db.commit()',
'    db.refresh(seat)',
'    return seat, None',
'',
'def release_expired_seats(db: Session):',
'    now = datetime.utcnow()',
'    expired = db.query(Seat).filter(',
'        Seat.status == SeatStatus.RESERVED,',
'        Seat.reserved_until < now',
'    ).all()',
'    count = 0',
'    for seat in expired:',
'        seat.status = SeatStatus.AVAILABLE',
'        seat.reserved_until = None',
'        count += 1',
'    db.commit()',
'    return count',
],
'app/api/v1/endpoints/seats.py': [
'from fastapi import APIRouter, Depends, HTTPException',
'from sqlalchemy.orm import Session',
'from uuid import UUID',
'from app.db.session import get_db',
'from app.services.seat_service import get_seat_map, reserve_seat_with_lock, release_expired_seats',
'',
'router = APIRouter()',
'',
'@router.get("/map/{schedule_id}")',
'def seat_map(schedule_id: UUID, db: Session = Depends(get_db)):',
'    result = get_seat_map(db, schedule_id)',
'    if not result["total"]:',
'        raise HTTPException(status_code=404, detail="Horario no encontrado")',
'    return result',
'',
'@router.post("/reserve/{seat_id}")',
'def reserve_seat(seat_id: UUID, db: Session = Depends(get_db)):',
'    seat, error = reserve_seat_with_lock(db, seat_id)',
'    if error:',
'        raise HTTPException(status_code=400, detail=error)',
'    return {',
'        "message": "Asiento reservado por 15 minutos",',
'        "seat_id": str(seat.id),',
'        "seat_number": seat.seat_number,',
'        "status": seat.status.value,',
'        "reserved_until": seat.reserved_until,',
'    }',
'',
'@router.post("/release-expired")',
'def release_expired(db: Session = Depends(get_db)):',
'    count = release_expired_seats(db)',
'    return {"message": f"{count} asientos liberados"}',
],
'app/api/v1/endpoints/bookings.py': [
'from fastapi import APIRouter, Depends, HTTPException',
'from sqlalchemy.orm import Session',
'from app.db.session import get_db',
'from app.schemas.booking import BookingCreate, BookingResponse',
'from app.services.booking_service import create_booking',
'from app.services.seat_service import release_expired_seats',
'from uuid import UUID',
'',
'router = APIRouter()',
'',
'@router.post("/", response_model=BookingResponse)',
'def book(data: BookingCreate, db: Session = Depends(get_db)):',
'    release_expired_seats(db)',
'    user_id = UUID("00000000-0000-0000-0000-000000000001")',
'    booking, error = create_booking(',
'        db=db,',
'        schedule_id=data.schedule_id,',
'        seat_id=data.seat_id,',
'        passenger_name=data.passenger_name,',
'        passenger_ci=data.passenger_ci,',
'        user_id=user_id,',
'    )',
'    if error:',
'        raise HTTPException(status_code=400, detail=error)',
'    return booking',
'',
'@router.get("/{booking_id}")',
'def get_booking(booking_id: UUID, db: Session = Depends(get_db)):',
'    from app.models.booking import Booking',
'    booking = db.query(Booking).filter(Booking.id == booking_id).first()',
'    if not booking:',
'        raise HTTPException(status_code=404, detail="Reserva no encontrada")',
'    return booking',
],
}

for filepath, lines in files.items():
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'OK: {filepath}')