import os

files = {
'app/services/route_service.py': [
'from sqlalchemy.orm import Session',
'from sqlalchemy import and_',
'from datetime import datetime',
'from app.models.schedule import Schedule',
'from app.models.route import Route',
'from app.models.bus import Bus',
'from app.models.seat import Seat, SeatStatus',
'',
'DEPARTAMENTOS = [',
'    "La Paz", "Santa Cruz", "Cochabamba",',
'    "Oruro", "Potosi", "Sucre", "Tarija"',
']',
'',
'def search_schedules(db: Session, origin: str, destination: str, date: str):',
'    search_date = datetime.strptime(date, "%Y-%m-%d")',
'    results = db.query(Schedule).join(Route).join(Bus).filter(',
'        and_(',
'            Route.origin == origin,',
'            Route.destination == destination,',
'            Schedule.departure_time >= search_date,',
'            Schedule.status == "active"',
'        )',
'    ).all()',
'    output = []',
'    for s in results:',
'        available = db.query(Seat).filter(',
'            Seat.schedule_id == s.id,',
'            Seat.status == SeatStatus.AVAILABLE',
'        ).count()',
'        item = {',
'            "id": s.id,',
'            "route_id": s.route_id,',
'            "bus_id": s.bus_id,',
'            "departure_time": s.departure_time,',
'            "arrival_time": s.arrival_time,',
'            "price_normal": s.price_normal,',
'            "price_semicama": s.price_semicama,',
'            "price_cama": s.price_cama,',
'            "terminal_fee": s.terminal_fee,',
'            "status": s.status.value,',
'            "available_seats": available,',
'            "origin": s.route.origin,',
'            "destination": s.route.destination,',
'            "company": s.bus.company,',
'            "bus_type": s.bus.bus_type.value,',
'            "duration_hours": s.route.duration_hours,',
'        }',
'        output.append(item)',
'    return output',
'',
'def get_departamentos():',
'    return DEPARTAMENTOS',
],
'app/services/booking_service.py': [
'from sqlalchemy.orm import Session',
'from sqlalchemy import select',
'from uuid import UUID',
'from datetime import datetime',
'from app.models.booking import Booking, BookingStatus',
'from app.models.seat import Seat, SeatStatus',
'from app.models.schedule import Schedule',
'from app.core.security import create_access_token',
'import uuid',
'',
'def get_seats_by_schedule(db: Session, schedule_id: UUID):',
'    return db.query(Seat).filter(Seat.schedule_id == schedule_id).all()',
'',
'def create_booking(db: Session, schedule_id: UUID, seat_id: UUID,',
'                   passenger_name: str, passenger_ci: str, user_id: UUID):',
'    seat = db.query(Seat).filter(',
'        Seat.id == seat_id,',
'        Seat.status == SeatStatus.AVAILABLE',
'    ).first()',
'    if not seat:',
'        return None, "Asiento no disponible"',
'    schedule = db.query(Schedule).filter(Schedule.id == schedule_id).first()',
'    if not schedule:',
'        return None, "Horario no encontrado"',
'    price_map = {',
'        "normal": schedule.price_normal,',
'        "semicama": schedule.price_semicama,',
'        "cama": schedule.price_cama,',
'    }',
'    base_price = price_map.get(schedule.bus.bus_type.value, schedule.price_normal)',
'    total = base_price + schedule.terminal_fee',
'    booking = Booking(',
'        id=uuid.uuid4(),',
'        user_id=user_id,',
'        schedule_id=schedule_id,',
'        seat_id=seat_id,',
'        passenger_name=passenger_name,',
'        passenger_ci=passenger_ci,',
'        base_price=base_price,',
'        terminal_fee=schedule.terminal_fee,',
'        total_price=total,',
'        status=BookingStatus.CONFIRMED,',
'    )',
'    qr_data = {"booking_id": str(booking.id), "ci": passenger_ci}',
'    booking.qr_token = create_access_token(qr_data)',
'    seat.status = SeatStatus.OCCUPIED',
'    db.add(booking)',
'    db.commit()',
'    db.refresh(booking)',
'    return booking, None',
],
'app/services/ticket_service.py': [
'from sqlalchemy.orm import Session',
'from uuid import UUID',
'from app.models.booking import Booking',
'from app.models.seat import Seat',
'from app.models.schedule import Schedule',
'from app.models.route import Route',
'from app.models.bus import Bus',
'',
'def get_ticket(db: Session, booking_id: UUID):',
'    booking = db.query(Booking).filter(Booking.id == booking_id).first()',
'    if not booking:',
'        return None',
'    schedule = db.query(Schedule).filter(Schedule.id == booking.schedule_id).first()',
'    route = db.query(Route).filter(Route.id == schedule.route_id).first()',
'    bus = db.query(Bus).filter(Bus.id == schedule.bus_id).first()',
'    seat = db.query(Seat).filter(Seat.id == booking.seat_id).first()',
'    return {',
'        "booking_id": booking.id,',
'        "passenger_name": booking.passenger_name,',
'        "passenger_ci": booking.passenger_ci,',
'        "origin": route.origin,',
'        "destination": route.destination,',
'        "departure_time": schedule.departure_time,',
'        "seat_number": seat.seat_number,',
'        "floor": seat.floor,',
'        "bus_type": bus.bus_type.value,',
'        "company": bus.company,',
'        "base_price": booking.base_price,',
'        "terminal_fee": booking.terminal_fee,',
'        "total_price": booking.total_price,',
'        "qr_token": booking.qr_token,',
'        "status": booking.status.value,',
'    }',
],
}

for filepath, lines in files.items():
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'OK: {filepath}')