files = {
'app/api/v1/endpoints/auth.py': [
'from fastapi import APIRouter, Depends, HTTPException, status',
'from sqlalchemy.orm import Session',
'from app.db.session import get_db',
'from app.models.user import User',
'from app.schemas.user import UserCreate, UserLogin, Token, UserResponse',
'from app.core.security import get_password_hash, verify_password, create_access_token',
'import uuid',
'',
'router = APIRouter()',
'',
'@router.post("/register", response_model=UserResponse)',
'def register(data: UserCreate, db: Session = Depends(get_db)):',
'    existing = db.query(User).filter(User.email == data.email).first()',
'    if existing:',
'        raise HTTPException(status_code=400, detail="Email ya registrado")',
'    existing_ci = db.query(User).filter(User.ci == data.ci).first()',
'    if existing_ci:',
'        raise HTTPException(status_code=400, detail="CI ya registrado")',
'    user = User(',
'        id=uuid.uuid4(),',
'        full_name=data.full_name,',
'        ci=data.ci,',
'        ci_extension=data.ci_extension,',
'        email=data.email,',
'        phone=data.phone,',
'        hashed_password=get_password_hash(data.password),',
'    )',
'    db.add(user)',
'    db.commit()',
'    db.refresh(user)',
'    return user',
'',
'@router.post("/login", response_model=Token)',
'def login(data: UserLogin, db: Session = Depends(get_db)):',
'    user = db.query(User).filter(User.email == data.email).first()',
'    if not user or not verify_password(data.password, user.hashed_password):',
'        raise HTTPException(status_code=401, detail="Credenciales invalidas")',
'    token = create_access_token({"sub": str(user.id)})',
'    return {"access_token": token, "token_type": "bearer", "user": user}',
],
'app/api/v1/endpoints/routes.py': [
'from fastapi import APIRouter, Depends',
'from sqlalchemy.orm import Session',
'from app.db.session import get_db',
'from app.services.route_service import get_departamentos, search_schedules',
'from app.schemas.route import SearchRequest',
'from typing import List',
'',
'router = APIRouter()',
'',
'@router.get("/departamentos")',
'def list_departamentos():',
'    return {"departamentos": get_departamentos()}',
'',
'@router.post("/search")',
'def search(data: SearchRequest, db: Session = Depends(get_db)):',
'    results = search_schedules(db, data.origin, data.destination, data.date)',
'    return {"results": results, "total": len(results)}',
],
'app/api/v1/endpoints/seats.py': [
'from fastapi import APIRouter, Depends',
'from sqlalchemy.orm import Session',
'from uuid import UUID',
'from app.db.session import get_db',
'from app.services.booking_service import get_seats_by_schedule',
'',
'router = APIRouter()',
'',
'@router.get("/{schedule_id}")',
'def get_seats(schedule_id: UUID, db: Session = Depends(get_db)):',
'    seats = get_seats_by_schedule(db, schedule_id)',
'    return {"seats": [',
'        {"id": str(s.id), "seat_number": s.seat_number,',
'         "floor": s.floor, "row": s.row,',
'         "column": s.column, "status": s.status.value}',
'        for s in seats',
'    ]}',
],
'app/api/v1/endpoints/bookings.py': [
'from fastapi import APIRouter, Depends, HTTPException',
'from sqlalchemy.orm import Session',
'from app.db.session import get_db',
'from app.schemas.booking import BookingCreate, BookingResponse',
'from app.services.booking_service import create_booking',
'from uuid import UUID',
'',
'router = APIRouter()',
'',
'@router.post("/", response_model=BookingResponse)',
'def book(data: BookingCreate, db: Session = Depends(get_db)):',
'    user_id = UUID("00000000-0000-0000-0000-000000000001")',
'    booking, error = create_booking(',
'        db=db,',
'        schedule_id=data.schedule_id,',
'        seat_id=data.seat_id,',
'        passenger_name=data.passenger_name,',
'        passenger_ci=data.passenger_ci,',
'        user_id=user_id,',
'    )',
'    if error:',
'        raise HTTPException(status_code=400, detail=error)',
'    return booking',
],
'app/api/v1/endpoints/tickets.py': [
'from fastapi import APIRouter, Depends, HTTPException',
'from sqlalchemy.orm import Session',
'from uuid import UUID',
'from app.db.session import get_db',
'from app.services.ticket_service import get_ticket',
'',
'router = APIRouter()',
'',
'@router.get("/{booking_id}")',
'def ticket(booking_id: UUID, db: Session = Depends(get_db)):',
'    result = get_ticket(db, booking_id)',
'    if not result:',
'        raise HTTPException(status_code=404, detail="Ticket no encontrado")',
'    return result',
],
'app/api/v1/endpoints/schedules.py': [
'from fastapi import APIRouter, Depends',
'from sqlalchemy.orm import Session',
'from app.db.session import get_db',
'from app.models.schedule import Schedule',
'',
'router = APIRouter()',
'',
'@router.get("/")',
'def list_schedules(db: Session = Depends(get_db)):',
'    schedules = db.query(Schedule).all()',
'    return {"total": len(schedules), "schedules": [str(s.id) for s in schedules]}',
],
}

for filepath, lines in files.items():
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'OK: {filepath}')