files = {
'app/utils/qr_generator.py': [
'import qrcode',
'import base64',
'from io import BytesIO',
'from app.core.security import decode_token',
'',
'def generate_qr_base64(token: str) -> str:',
'    qr = qrcode.QRCode(version=1, box_size=10, border=4)',
'    qr.add_data(token)',
'    qr.make(fit=True)',
'    img = qr.make_image(fill_color="black", back_color="white")',
'    buffer = BytesIO()',
'    img.save(buffer, format="PNG")',
'    buffer.seek(0)',
'    return base64.b64encode(buffer.getvalue()).decode("utf-8")',
'',
'def validate_qr_token(token: str) -> dict:',
'    payload = decode_token(token)',
'    if not payload:',
'        return None',
'    return payload',
],
'app/utils/pdf_generator.py': [
'from reportlab.lib.pagesizes import A4',
'from reportlab.lib import colors',
'from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle',
'from reportlab.lib.units import cm',
'from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image',
'from reportlab.lib.enums import TA_CENTER, TA_LEFT',
'from io import BytesIO',
'import base64',
'import qrcode',
'from datetime import datetime',
'',
'def generate_ticket_pdf(ticket_data: dict) -> bytes:',
'    buffer = BytesIO()',
'    doc = SimpleDocTemplate(',
'        buffer,',
'        pagesize=A4,',
'        rightMargin=2*cm,',
'        leftMargin=2*cm,',
'        topMargin=2*cm,',
'        bottomMargin=2*cm',
'    )',
'    styles = getSampleStyleSheet()',
'    navy = colors.HexColor("#1B2A6B")',
'    red = colors.HexColor("#C8102E")',
'    gold = colors.HexColor("#D4AF37")',
'    title_style = ParagraphStyle("title", parent=styles["Heading1"], textColor=colors.white, fontSize=20, alignment=TA_CENTER)',
'    label_style = ParagraphStyle("label", parent=styles["Normal"], textColor=navy, fontSize=9, fontName="Helvetica-Bold")',
'    value_style = ParagraphStyle("value", parent=styles["Normal"], textColor=colors.black, fontSize=11)',
'    elements = []',
'    header_data = [[Paragraph("BOLIVIA BUS", title_style)], [Paragraph("Ticket de Viaje", ParagraphStyle("sub", parent=styles["Normal"], textColor=gold, fontSize=12, alignment=TA_CENTER))]]',
'    header_table = Table(header_data, colWidths=[17*cm])',
'    header_table.setStyle(TableStyle([',
'        ("BACKGROUND", (0,0), (-1,-1), navy),',
'        ("ALIGN", (0,0), (-1,-1), "CENTER"),',
'        ("TOPPADDING", (0,0), (-1,-1), 12),',
'        ("BOTTOMPADDING", (0,0), (-1,-1), 12),',
'        ("ROUNDEDCORNERS", [8]),',
'    ]))',
'    elements.append(header_table)',
'    elements.append(Spacer(1, 0.5*cm))',
'    dep = datetime.strptime(str(ticket_data["departure_time"]), "%Y-%m-%d %H:%M:%S") if isinstance(ticket_data["departure_time"], str) else ticket_data["departure_time"]',
'    info_data = [',
'        [Paragraph("PASAJERO", label_style), Paragraph(ticket_data["passenger_name"].upper(), value_style)],',
'        [Paragraph("CI", label_style), Paragraph(ticket_data["passenger_ci"], value_style)],',
'        [Paragraph("RUTA", label_style), Paragraph(f"{ticket_data[chr(111)+chr(114)+chr(105)+chr(103)+chr(105)+chr(110)]} -> {ticket_data[chr(100)+chr(101)+chr(115)+chr(116)+chr(105)+chr(110)+chr(97)+chr(116)+chr(105)+chr(111)+chr(110)]}", value_style)],',
'        [Paragraph("SALIDA", label_style), Paragraph(dep.strftime("%d/%m/%Y %H:%M"), value_style)],',
'        [Paragraph("ASIENTO", label_style), Paragraph(f"{ticket_data[chr(115)+chr(101)+chr(97)+chr(116)+chr(95)+chr(110)+chr(117)+chr(109)+chr(98)+chr(101)+chr(114))]} - Piso {ticket_data[chr(102)+chr(108)+chr(111)+chr(111)+chr(114)]}", value_style)],',
'        [Paragraph("BUS", label_style), Paragraph(f"{ticket_data[chr(99)+chr(111)+chr(109)+chr(112)+chr(97)+chr(110)+chr(121))]} ({ticket_data[chr(98)+chr(117)+chr(115)+chr(95)+chr(116)+chr(121)+chr(112)+chr(101)]})", value_style)],',
'        [Paragraph("PRECIO BASE", label_style), Paragraph(f"Bs. {ticket_data[chr(98)+chr(97)+chr(115)+chr(101)+chr(95)+chr(112)+chr(114)+chr(105)+chr(99)+chr(101)]:.2f}", value_style)],',
'        [Paragraph("DERECHO TERMINAL", label_style), Paragraph(f"Bs. {ticket_data[chr(116)+chr(101)+chr(114)+chr(109)+chr(105)+chr(110)+chr(97)+chr(108)+chr(95)+chr(102)+chr(101)+chr(101)]:.2f}", value_style)],',
'        [Paragraph("TOTAL", label_style), Paragraph(f"Bs. {ticket_data[chr(116)+chr(111)+chr(116)+chr(97)+chr(108)+chr(95)+chr(112)+chr(114)+chr(105)+chr(99)+chr(101)]:.2f}", value_style)],',
'    ]',
'    info_table = Table(info_data, colWidths=[5*cm, 12*cm])',
'    info_table.setStyle(TableStyle([',
'        ("GRID", (0,0), (-1,-1), 0.5, colors.lightgrey),',
'        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#F0F4FF")),',
'        ("TOPPADDING", (0,0), (-1,-1), 8),',
'        ("BOTTOMPADDING", (0,0), (-1,-1), 8),',
'        ("LEFTPADDING", (0,0), (-1,-1), 10),',
'    ]))',
'    elements.append(info_table)',
'    elements.append(Spacer(1, 0.5*cm))',
'    qr = qrcode.QRCode(version=1, box_size=6, border=2)',
'    qr.add_data(ticket_data["qr_token"])',
'    qr.make(fit=True)',
'    qr_img = qr.make_image(fill_color="black", back_color="white")',
'    qr_buffer = BytesIO()',
'    qr_img.save(qr_buffer, format="PNG")',
'    qr_buffer.seek(0)',
'    qr_rl = Image(qr_buffer, width=4*cm, height=4*cm)',
'    qr_table = Table([[qr_rl, Paragraph("Presenta este QR\\nal conductor para\\nvalidar tu pasaje.", ParagraphStyle("qr_text", parent=styles["Normal"], fontSize=10, textColor=navy))]], colWidths=[5*cm, 12*cm])',
'    qr_table.setStyle(TableStyle([',
'        ("ALIGN", (0,0), (0,0), "CENTER"),',
'        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),',
'        ("BOX", (0,0), (-1,-1), 1, navy),',
'        ("TOPPADDING", (0,0), (-1,-1), 10),',
'        ("BOTTOMPADDING", (0,0), (-1,-1), 10),',
'    ]))',
'    elements.append(qr_table)',
'    elements.append(Spacer(1, 0.3*cm))',
'    footer = Paragraph("Bolivia Bus | Sistema Integral de Ticketing Terrestre | boliviabus.bo", ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=TA_CENTER))',
'    elements.append(footer)',
'    doc.build(elements)',
'    buffer.seek(0)',
'    return buffer.getvalue()',
],
}

for filepath, lines in files.items():
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'OK: {filepath}')