"""schema_v4

Revision ID: 93a135d5e6d2
Revises: 
Create Date: 2026-04-29 14:46:29.704808

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '93a135d5e6d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('color_flota', sa.String(length=7), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_table('terminals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('ci', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('pasajero', 'admin', 'chofer', name='rolusuario'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('buses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.Enum('normal', 'semicama', 'cama', 'doble_piso', name='tipobus'), nullable=True),
    sa.Column('total_asientos', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('licencia', sa.String(length=20), nullable=True),
    sa.Column('pin_hash', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('terminal_origen_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('terminal_destino_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['terminal_destino_id'], ['terminals.id'], ),
    sa.ForeignKeyConstraint(['terminal_origen_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal_services',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('terminal_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo', sa.Enum('cajero', 'consultorio', 'food_court', 'gimnasio', 'comercio', 'preembarque', 'bano', 'informacion', name='tiposervicio'), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('horario', sa.String(length=80), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bus_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('driver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_llegada_est', sa.DateTime(timezone=True), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('programado', 'en_ruta', 'completado', 'cancelado', name='estadohorario'), nullable=True),
    sa.Column('asientos_disponibles', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bus_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('numero', sa.String(length=5), nullable=False),
    sa.Column('fila', sa.String(length=3), nullable=False),
    sa.Column('columna', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('normal', 'semicama', 'cama', name='tipoasiento'), nullable=True),
    sa.Column('piso', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schedule_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('codigo_reserva', sa.String(length=12), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagada', 'cancelada', 'completada', name='estadoreserva'), nullable=True),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_reserva')
    )
    op.create_table('gps_tracking',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schedule_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bus_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('velocidad_kmh', sa.Float(), nullable=True),
    sa.Column('rumbo', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'qr', 'tarjeta', 'transferencia', name='metodopago'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'completado', 'fallido', 'reembolsado', name='estadopago'), nullable=True),
    sa.Column('referencia_ext', sa.String(length=100), nullable=True),
    sa.Column('pagado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seat_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pasajero_nombre', sa.String(length=120), nullable=False),
    sa.Column('pasajero_ci', sa.String(length=20), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('qr_code', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'usado', 'cancelado', name='estadoticket'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_table('gps_tracking')
    op.drop_table('bookings')
    op.drop_table('seats')
    op.drop_table('schedules')
    op.drop_table('terminal_services')
    op.drop_table('routes')
    op.drop_table('drivers')
    op.drop_table('buses')
    op.drop_table('users')
    op.drop_table('terminals')
    op.drop_table('companies')
    # ### end Alembic commands ###